#修改监控端口
server:
  port: 9041

#logging:
 # level:
  #  org:
   #   springframework:
    #    security: DEBUG
#
 # pattern:
  #  console: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level %X{requestId} %logger{15} - %msg%n'


logging:
  config: classpath:log4j2-dev.yml